/*
 * DO NOT MODIFY.
 *
 * This file was generated by arch/um/Makefile
 *
 */

#define HOST_SC_IP 56 /* offsetof(struct sigcontext, eip)	# */
#define HOST_SC_SP 28 /* offsetof(struct sigcontext, esp)	# */
#define HOST_SC_FS 4 /* offsetof(struct sigcontext, fs)	# */
#define HOST_SC_GS 0 /* offsetof(struct sigcontext, gs)	# */
#define HOST_SC_DS 12 /* offsetof(struct sigcontext, ds)	# */
#define HOST_SC_ES 8 /* offsetof(struct sigcontext, es)	# */
#define HOST_SC_SS 72 /* offsetof(struct sigcontext, ss)	# */
#define HOST_SC_CS 60 /* offsetof(struct sigcontext, cs)	# */
#define HOST_SC_EFLAGS 64 /* offsetof(struct sigcontext, eflags)	# */
#define HOST_SC_EAX 44 /* offsetof(struct sigcontext, eax)	# */
#define HOST_SC_EBX 32 /* offsetof(struct sigcontext, ebx)	# */
#define HOST_SC_ECX 40 /* offsetof(struct sigcontext, ecx)	# */
#define HOST_SC_EDX 36 /* offsetof(struct sigcontext, edx)	# */
#define HOST_SC_EDI 16 /* offsetof(struct sigcontext, edi)	# */
#define HOST_SC_ESI 20 /* offsetof(struct sigcontext, esi)	# */
#define HOST_SC_EBP 24 /* offsetof(struct sigcontext, ebp)	# */
#define HOST_SC_TRAPNO 48 /* offsetof(struct sigcontext, trapno)	# */
#define HOST_SC_ERR 52 /* offsetof(struct sigcontext, err)	# */
#define HOST_SC_CR2 84 /* offsetof(struct sigcontext, cr2)	# */
#define HOST_SC_FPSTATE 76 /* offsetof(struct sigcontext, fpstate)	# */
#define HOST_SC_SIGMASK 80 /* offsetof(struct sigcontext, oldmask)	# */
#define HOST_SC_FP_CW 0 /* offsetof(struct _fpstate, cw)	# */
#define HOST_SC_FP_SW 4 /* offsetof(struct _fpstate, sw)	# */
#define HOST_SC_FP_TAG 8 /* offsetof(struct _fpstate, tag)	# */
#define HOST_SC_FP_IPOFF 12 /* offsetof(struct _fpstate, ipoff)	# */
#define HOST_SC_FP_CSSEL 16 /* offsetof(struct _fpstate, cssel)	# */
#define HOST_SC_FP_DATAOFF 20 /* offsetof(struct _fpstate, dataoff)	# */
#define HOST_SC_FP_DATASEL 24 /* offsetof(struct _fpstate, datasel)	# */
#define HOST_SC_FP_ST 28 /* offsetof(struct _fpstate, _st)	# */
#define HOST_SC_FXSR_ENV 112 /* offsetof(struct _fpstate, _fxsr_env)	# */
#define HOST_FP_SIZE 27 /* sizeof(struct user_i387_struct)	# */
#define HOST_XFP_SIZE 128 /* sizeof(struct user_fxsr_struct)	# */
#define HOST_IP 12 /* EIP	# */
#define HOST_SP 15 /* UESP	# */
#define HOST_EFLAGS 14 /* EFL	# */
#define HOST_EAX 6 /* EAX	# */
#define HOST_EBX 0 /* EBX	# */
#define HOST_ECX 1 /* ECX	# */
#define HOST_EDX 2 /* EDX	# */
#define HOST_ESI 3 /* ESI	# */
#define HOST_EDI 4 /* EDI	# */
#define HOST_EBP 5 /* EBP	# */
#define HOST_CS 13 /* CS	# */
#define HOST_SS 16 /* SS	# */
#define HOST_DS 7 /* DS	# */
#define HOST_FS 9 /* FS	# */
#define HOST_ES 8 /* ES	# */
#define HOST_GS 10 /* GS	# */
#define UM_FRAME_SIZE 68 /* sizeof(struct user_regs_struct)	# */
#define UM_POLLIN 1 /* POLLIN	# */
#define UM_POLLPRI 2 /* POLLPRI	# */
#define UM_POLLOUT 4 /* POLLOUT	# */
#define UM_PROT_READ 1 /* PROT_READ	# */
#define UM_PROT_WRITE 2 /* PROT_WRITE	# */
#define UM_PROT_EXEC 4 /* PROT_EXEC	# */

